### ISSUE TITLE
함께 자라기 애자일로 가는 길

### ISSUE THREAD

**Issue by riflockle7** [Nexters/READ-BOOK#162]
![image](https://user-images.githubusercontent.com/13694046/125226054-4d8a8080-e30b-11eb-8049-b8a4bc307d82.png)
## 저자
김창준

## 책 개요
모두가 함께 발전하기 위한 제안
‘함께’는 협력을 말하고, ‘자라기’는 학습을 말합니다. 무엇이건 실제 바깥세상(야생)에 임팩트를 남기려면 혼자 힘으로만 되는 게 없습니다. 함께 해야 합니다. 주변 사람들과 함께. 매일 부대끼는 동료들과 함께. 스스로 변하고 싶지만 계속 실패하는 사람, 조직을 개선하기 위한 시도를 하다가 오히려 데어본 사람, 불확실한 상황에서 합리적인 판단을 해야 하는 사람, 한 분야에서 전문성을 키워야 하는 사람에게 전문성을 키울 수 있는 제대로 된 방법을 알려줍니다. 어떤 분야에서 일하든 어느 위치에 있든 상관 없습니다. 이 책에서는 일하는 방법의 핵심과 통찰을 다룹니다. 개인의 힘으로는 극복할 수 없는 한계를 깨뜨리려면 모두가 같이 발전해야 합니다. 나 그리고 더 나아가 남을 변화시키는 삶에 대해 얘기합니다.

- 직원을 뽑을 때 무엇이 그 사람의 실력을 가장 잘 예측할까
- 수십 년 같은 일을 해도 전문가가 안 되는 이유와 제자리걸음에서 벗어나는 방법
- 커뮤니케이션과 협력을 잘하는 방안
- 리더의 역할과, 멘토링, 코칭 능력을 향상시키려면?
- 빠른 학습 능력을 보이는 탁월한 팀의 비밀
- 조직을 효과적으로 변화시키려면?

## 책 구매 링크
http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9788966262335#N

**Comment by sbyeol3** [comment]
오.. 저 이거 읽고 싶어요 !!! 상우님은 소프트스킬에 관심이 많으시군요 👍 👀

**Comment by riflockle7** [comment]
읽기 완료
