### ISSUE TITLE
소프트 스킬 (평범한 개발자의 비범한 인생 전략 71가지)

### ISSUE THREAD

**Issue by riflockle7** [Nexters/READ-BOOK#34]
# 책소개 및 [링크](http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9791186659885&orderClick=LAG&Kc=#N)
카테고리 : IT교양서/IT에세이

저자 존 손메즈가 이 책을 쓴 이유는 개발자로 사는 데 도움이 되는 정보와 조언을 집약적으로 담은 안내서를 만들고 싶어서다.  
자신이 33세에 은퇴하기까지 성공과 실패를 통해 배운 것, 여러 사람을 만나면서 보고 들으며 배운 것을 전달하고 공유하기 위해서다.  
개발자의 인생을 리부트할 조언들로 꽉 차있다.

![image](http://image.kyobobook.co.kr/images/book/large/885/l9791186659885.jpg)

**Comment by riflockle7** [comment]
아직 마지막 과가 남아있어 reopen 처리함 (2주내로 마지막 과 읽을 예정 ㅇㅅㅇ...)

**Comment by sbyeol3** [comment]
저 이거 올해 안에 읽어볼 예정입니다...!!!!!

**Comment by riflockle7** [comment]
읽기 완료
